@startuml
actor User

participant ":CommandHandler" as CH
participant ":ExpenseManager" as EM
participant ":Expense" as Exp

User -> CH : handleAddExpense(expenseName, amount, category)
activate CH
CH -> EM : addExpense(expenseName, amount, category)
activate EM

EM -> EM : Check if expense name is empty\nand if duplicate exists
EM -> EM : createCategory(category)
activate EM
EM --> EM : createCategory(category) completes
deactivate EM

EM -> Exp : new Expense
activate Exp
deactivate Exp

EM -> EM : Add Expense to expenses list\nUpdate totalExpense
deactivate EM

CH --> User : message
deactivate CH
@enduml
