@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam classIconSize 0

package expenses {
    enum "<<enumeration>> \n Currency"  as Currency {
      --
      IDR
      LAK
      MYR
      PHP
      SGD
      THB
      VND
      USD
      EUR
      JPY
      GBP
      ' Attributes
      --
      - name : String
      - rate : double
      ' Methods
      --
      + convert(amount: double) : double
    }

    class Expense {
      {static} FORMATTER : DateTimeFormatter
      - name : String
      - amount : double
      - category : String
      - dateTime : LocalDateTime

    }

    class "<<singleton>> \n ExpenseManager" as ExpenseManager {
    - budget : double
    - totalExpense: double
    - categories[]: String[]
    - baseCurrency: Currency

    + createCategory(categoryName: String): void
    + addExpense(name: String, amount: double): void
    + addExpense(name: String, amount: double, (categoryName: String): void
    + deleteExpense(id: int): void
    + deleteExpense(expenseName: String): void
    + getExpensesByCategory(category: String): Expense[]
    + setExpenseCategory(expenseName: String, category: String): void
    + getMaxExpense(): Expense
    + getMinExpense(): Expense
    + getExpensesByDateRange(start: LocalDateTime, end: LocalDateTime): Expense[]
    }
   }


ExpenseManager *--> "expenses" Expense
ExpenseManager --> "baseCurrency" Currency


@enduml